### ISSUE TITLE
Tomcat password not found

### ISSUE THREAD

**Issue by AlessandroZ** [ztgrace/changeme#16]
Hi,

I have installed  a Tomcat server to test this module. However, the password has not been found. I have checked why and it is because the string "Tomcat Web Application Manager" is not present, but I have some other string such as "Welcome to Tomcat" that I can add 

I think if you put that string is because it was present on your tomcat instance. So my idea was to change the schema of "body" to use list and not string. The user could add many trigger string and if one match the credentials are ok: 
```
success:
    body: 
      - Welcome to Tomcat
      - Tomcat Web Application Manager
    status: 200
```
Moreover, I think this field should not be always required. For example only the status code could be checked for Tomcat (if it's equal to 200 it's ok). It could avoid false positive for this module (and maybe others).

If your ok to these modification I could do it. However, it will affect all yaml files so I want to be sure that you're ok about that.
